name: weather_repository
description:
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  open_weather_api:
    path: ../open_weather_api
  json_annotation: ^4.9.0
  equatable: ^2.0.7

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
