name: open_weather_api
description:
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  http: ^1.2.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  mocktail: ^1.0.4
  test: ^1.25.14
